# config.yml

backend:
  name: 'github'
  repo: prodigy2m/digitalobster.com
  branch: master # Branch to update (optional; defaults to master)
  base_url: '/'
  local_backend: true
publish_mode: editorial_workflow
media_folder: 'assets/images'

collections:
  - name: 'static_pages'
    label: 'Static Pages'
    icon: pin
    folder: "content/homepages/"
    path: '/'
    editor:
      preview: false
    value_field: "slogan"
    displayFields: ['slogan']
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{meta.slogan}}: {{title}}' 
    fields:
      - label: "Published"
        name: "published"
        widget: "boolean"
        default: false
        required: false
      - label: "Permalink"
        name: "permalink"
        widget: "string"
        required: false
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
      - label: "Tags"
        name: "tags"
        widget: "text"
        required: false
      - label: "Slogan"
        name: "slogan"
        widget: "string"
        required: false